pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        google()
        jcenter()
        mavenCentral()
        gradlePluginPortal()
        flatDir {
            dirs "${rootDir}/libs"
        }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter()
        flatDir {
            dirs "${rootDir}/libs"
        }
    }

}

rootProject.name = "LiveTv Port"
include ':app', ':common', ':partner_support'
include ':jni'//, ':jni:minijail'

